version: '3'

services:
  app:
    image: reactive_es_demo
    build:
      context: ../
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
